name 'ramgop-buildserver'
version '0.0.1'
author 'ramgop'
summary 'Configuration for kickstart/preceed server'
description 'Longer description of the module including an example'
license 'The license the module is release under - generally GPLv2 or Apache'
project_page 'https://github.com/ramgop/buildserver'
